### ISSUE TITLE
Portal api feature requests

### ISSUE THREAD

**Issue by 7neyugn7** [UQ-RCC/nimrodg#23]
1. Experiment
- [ ] list job-related stats with jobs belong to an experiment and their status
- [x] list number of agents belong to an experiment
- [ ] list cpu hours based on resource type
- [ ] mean, median jobs

2. Resource 
- [ ] show the number of CPU hours being used so far for each resource
- [ ] show the total number of successful jobs, failed jobs
- [ ] mean, median jobs
- [ ] add resource with portalapi similar to nimrod api 
3. plan file
- [x] compile returns 0 even when compile command fails

And more

**Comment by vs49688** [comment]
`list jobs belong to an experiment and their status`

This could get really big, really quickly. I'd much prefer wrapping `Experiment#filterJobs` than doing a full query. Can the portal handle that?

```java
/**
 * Get a list of jobs that satisfy the given criteria.
 *
 * This list may not be modified.
 *
 * @param status The statuses of the jobs.
 * @param start The lowest possible starting number for the job.
 * @param limit The maximum number of jobs to return. Set to 0 for no limit.
 * @return An immutable list of jobs that satisfy the given criteria.
 */
Collection<Job> filterJobs(EnumSet<JobAttempt.Status> status, long start, int limit);
```

**Comment by vs49688** [comment]
PortalAPI is deprecated
