### ISSUE TITLE
Portal api get resources output change request

### ISSUE THREAD

**Issue by 7neyugn7** [UQ-RCC/nimrodg#24]
Currently, nimrod portalapi getresources returns 

> name,path,config,tx_uri,tx_cert,tx_no_verify_peer,tx_no_verify_host

Please add type into the output. Or replace path with type.

**Comment by vs49688** [comment]
This is done, but just so you're aware this contains the typename, so `hpc`, `local`, etc. For the portal, if you mean the hpc type, you'll have to look in the JSON in the `config` field.

See the `hpc_cluster_resource` section in https://github.com/UQ-RCC/nimrodg/blob/master/nimrodg-resources/src/main/resources/au/edu/uq/rcc/nimrodg/resource/resource_base.json
